logging:
  level:
    org.springframework.web: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todoapp
    username: root
    password: qwer1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect